"""add expiration date to items

Revision ID: e2fac8ee46c0
Revises: b46d81f0ee0f
Create Date: 2026-09-29 20:24:10.615396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2fac8ee46c0'
down_revision: Union[str, Sequence[str], None] = 'b46d81f0ee0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('expiration_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'expiration_date')
    # ### end Alembic commands ###
