"""add item soft-delete field

Revision ID: fcbfa9422112
Revises: a6f31c2d9b40
Create Date: 2026-10-09 14:57:16.311848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbfa9422112'
down_revision: Union[str, Sequence[str], None] = 'a6f31c2d9b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'deleted_at')
    op.drop_column('items', 'deleted')
    # ### end Alembic commands ###
